controller_frequency: 6
planner_frequency: 0.1
recovery_behavior_enabled: true
clearing_rotation_allowed: true

TrajectoryPlannerROS:
   max_vel_x: 0.5
   min_vel_x: -0.5
   max_vel_y: 0.0  # zero for a differential drive robot
   min_vel_y: 0.0
   max_vel_theta: 1.0
   min_vel_theta: -1.0
   min_in_place_vel_theta: 0.7
   escape_vel: -0.1
   acc_lim_x: 25
   acc_lim_y: 0.0 # zero for a differential drive robot
   acc_lim_theta: 3.5

   holonomic_robot: false
   yaw_goal_tolerance: 0.05
   xy_goal_tolerance: 0.05
   latch_xy_goal_tolerance: true
   pdist_scale: 0.9
   gdist_scale: 0.8
   meter_scoring: true

# Trajectory Scoring Parameters
   heading_lookahead: 0.325
   heading_scoring: false
   heading_scoring_timestep: 0.8
   occdist_scale: 0.02  #定义控制器躲避障碍物的程度
   oscillation_reset_dist: 0.05  #机器人运动多远距离才会重置振荡标记
   publish_cost_grid_pc: false
   prune_plan: true

   sim_time: 0.8
   sim_granularity: 0.025
   angular_sim_granularity: 0.025
   vx_samples: 5
   vy_samples: 0 # zero for a differential drive robot
   vtheta_samples: 15
   dwa: true
   simple_attractor: false
